<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.11" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="Governance.fs" />
    <Compile Include="Cli.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>

</Project>
