// Unit-layer step bindings for the `@vitest-unit` scenarios of
// specs/apps/bnest/app-be/behaviours/family_chat_operations.feature: the reverse-proxy
// configuration the deployment tool writes into Caddy.
//
// The configuration is generated by `tools/caddy-config.mjs`, the module
// `tools/deployment.mjs` imports to write it, called here in process. The Elixir unit
// layer may not start a Node process, so these scenarios' unit layer lives in this
// harness, and `BnestApp.Behaviour.FeVitestUnitScope.prune_unit_layer/1` drops them from
// the Elixir unit layer; their integration layer stays Elixir ExBdd, which runs the same
// module with Node.

import type { StepDefinition, StepHandler } from "./family_chat.steps";

type CaddyConfig = typeof import("../../../tools/caddy-config.mjs");

const registry: StepDefinition[] = [];

function step(expression: string, handler: StepHandler): void {
  registry.push({ expression, handler });
}

export function familyChatOperationsSteps(): readonly StepDefinition[] {
  return registry;
}

// Resolved against this module's own URL, like the sibling step files' imports.
const CADDY_CONFIG = new URL("../../../tools/caddy-config.mjs", import.meta.url)
  .href;

interface GeneratedConfig {
  readonly slot: string;
  readonly port: number;
  readonly healthChecked: boolean;
  readonly config: string;
}

interface Promotion {
  readonly promotedPort: number;
  readonly priorPort: number;
  readonly config: string;
}

async function generatedConfigs(): Promise<GeneratedConfig[]> {
  const { caddyfile, slots } = (await import(CADDY_CONFIG)) as CaddyConfig;
  const configs: GeneratedConfig[] = [];
  for (const [slot, port] of Object.entries(slots)) {
    for (const healthChecked of [true, false]) {
      configs.push({
        slot,
        port,
        healthChecked,
        config: caddyfile(slot as keyof typeof slots, healthChecked),
      });
    }
  }
  return configs;
}

function fail(message: string): never {
  throw new Error(message);
}

function configsOf(context: Record<string, unknown>): GeneratedConfig[] {
  const configs = context["generatedConfigs"] as GeneratedConfig[] | undefined;
  if (configs === undefined || configs.length === 0)
    fail("no reverse-proxy configuration was generated");
  return configs;
}

function promotionsOf(context: Record<string, unknown>): Promotion[] {
  const promotions = context["promotions"] as Promotion[] | undefined;
  if (promotions === undefined || promotions.length === 0)
    fail("no promotion configuration was generated");
  return promotions;
}

// The directives of a configuration's leading global options block, trimmed.
function globalOptions(config: string): string[] {
  if (!config.startsWith("{\n")) return [];
  const [block = ""] = config.slice(2).split("\n}\n", 1);
  return block.split("\n").map((line) => line.trim());
}

// The upstreams of every `reverse_proxy` directive in a configuration.
function reverseProxyUpstreams(config: string): string[][] {
  return [
    ...config.matchAll(/^\s*reverse_proxy\s+([^{\n]*?)\s*\{?\s*$/gmu),
  ].map((match) =>
    (match[1] ?? "").split(/\s+/u).filter((token) => token !== ""),
  );
}

step(
  "the deployment tool generates the reverse-proxy configuration for a release",
  async (context) => ({
    ...context,
    generatedConfigs: await generatedConfigs(),
  }),
);

step(
  "the generated configuration omits {string} and any other nonzero stream-close delay",
  (context, setting) => {
    for (const { slot, healthChecked, config } of configsOf(context)) {
      if (
        setting === undefined ||
        config.includes(setting) ||
        config.includes("stream_close")
      )
        fail(
          `the ${slot} configuration (health check ${healthChecked}) sets a stream-close delay`,
        );
    }
    return context;
  },
);

step(
  "the existing global five-minute grace period remains present",
  (context) => {
    for (const { slot, healthChecked, config } of configsOf(context)) {
      if (!globalOptions(config).includes("grace_period 5m"))
        fail(
          `the ${slot} configuration (health check ${healthChecked}) has no global five-minute grace period`,
        );
    }
    return context;
  },
);

// What a promotion writes: the health-checked configuration for the slot it promotes,
// for each slot promoted over the other one.
step(
  "the deployment tool generates the reverse-proxy configuration that promotes the replacement slot",
  async (context) => {
    const configs = await generatedConfigs();
    const promotions: Promotion[] = [];
    for (const promoted of configs.filter((config) => config.healthChecked)) {
      for (const prior of configs) {
        if (prior.slot !== promoted.slot && prior.healthChecked)
          promotions.push({
            promotedPort: promoted.port,
            priorPort: prior.port,
            config: promoted.config,
          });
      }
    }
    return { ...context, promotions };
  },
);

step(
  "every replacement handshake is routed only to the promoted slot",
  (context) => {
    for (const { promotedPort, config } of promotionsOf(context)) {
      const upstreams = JSON.stringify(reverseProxyUpstreams(config));
      if (upstreams !== JSON.stringify([[`127.0.0.1:${promotedPort}`]]))
        fail(`promoting port ${promotedPort} routes to ${upstreams}`);
    }
    return context;
  },
);

step("no routed handshake reaches the prior slot", (context) => {
  for (const { priorPort, config } of promotionsOf(context)) {
    if (config.includes(`:${priorPort}`))
      fail(`the promotion configuration still names prior port ${priorPort}`);
  }
  return context;
});
