defmodule BnestAppWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :bnest_app
  use Absinthe.Phoenix.Endpoint

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_bnest_app_key",
    signing_salt: "GMjl1ern",
    same_site: "Lax"
  ]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # `familyChatMessageCommitted` subscriptions. Identity is server-decoded from
  # the same signed session cookie as HTTP (`connect_info: [session: ...]`);
  # `UserSocket.connect/3` never trusts socket params for identity.
  #
  # `check_csrf: false`: Phoenix's `connect_info: [session: ...]` decoding
  # defaults to requiring a `_csrf_token` *query param* matching the session
  # (`Phoenix.Socket.Transport.connect_session/4`) — a plain WebSocket
  # upgrade never carries one, so the session would silently decode to `nil`
  # regardless of a genuinely valid identity cookie, and every handshake
  # would be refused. Tech-doc 008 documents only session + origin defenses
  # for this socket (never a CSRF token) — CSRF protection remains enforced
  # separately, and unconditionally, for every GraphQL HTTP mutation via
  # `BnestAppWeb.Plugs.GraphQLPipeline`.
  #
  # `check_origin: true`: tech-doc 008 documents "endpoint origin checking"
  # as this socket's other handshake defense alongside the session cookie
  # (since `check_csrf` is off). Set explicitly so it holds regardless of
  # `config/dev.exs`'s endpoint-wide `check_origin: false` (a convenience
  # for plain page/LiveView browsing in dev) — Phoenix 1.8's own transport
  # validator now refuses to boot a socket where both would end up `false`.
  socket "/api/graphql/socket", BnestAppWeb.UserSocket,
    websocket: [
      connect_info: [session: @session_options],
      check_csrf: false,
      check_origin: true
    ],
    longpoll: false

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :bnest_app,
    gzip: not code_reloading?,
    only: BnestAppWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options
  plug BnestAppWeb.ReleaseHeaders
  plug BnestAppWeb.Router
end
