defmodule BnestApp.Behaviour.Driver do
  @moduledoc false

  @callback open(map(), String.t()) :: map()
  @callback brand_logo_visible?(map()) :: boolean()
  @callback installable_as_app?(map()) :: boolean()
  @callback heading_visible?(map(), String.t()) :: boolean()
  @callback text_visible?(map(), String.t()) :: boolean()
  @callback chat_entry_link_visible?(map(), String.t(), String.t()) :: boolean()
  @callback data_migration_entry_absent?(map()) :: boolean()
  @callback model_selector_lists_all?(map()) :: boolean()
  @callback selected_model?(map(), String.t()) :: boolean()
  @callback effort_selector_lists_supported?(map()) :: boolean()
  @callback selected_effort?(map(), String.t()) :: boolean()
  @callback model_selector_available?(map()) :: boolean()
  @callback model_selector_unavailable?(map()) :: boolean()
  @callback effort_selector_available?(map()) :: boolean()
  @callback effort_selector_unavailable?(map()) :: boolean()
  @callback select_model(map(), String.t()) :: map()
  @callback select_effort(map(), String.t()) :: map()
  @callback conversation_empty?(map()) :: boolean()
  @callback composer_available?(map()) :: boolean()
  @callback composer_unavailable?(map()) :: boolean()
  @callback clear_chat_control_available?(map()) :: boolean()
  @callback attempt_empty_message(map()) :: map()
  @callback send_message(map(), String.t()) :: map()
  @callback submit_with_shift_enter(map(), String.t()) :: map()
  @callback attempt_message_before_finished(map(), String.t()) :: map()
  @callback visitor_message_visible?(map(), String.t()) :: boolean()
  @callback visitor_message_absent?(map(), String.t()) :: boolean()
  @callback stream_codex_response(map()) :: {boolean(), map()}
  @callback one_completed_codex_response_visible?(map()) :: boolean()
  @callback second_codex_response_visible?(map()) :: boolean()
  @callback reject_message(map(), String.t()) :: map()
  @callback report_codex_error(map(), String.t()) :: map()
  @callback alert_visible?(map(), String.t()) :: boolean()
  @callback reload(map()) :: map()
  @callback clear_chat(map()) :: map()
  @callback study_mode_available?(map()) :: boolean()
  @callback quiz_mode_available?(map()) :: boolean()
  @callback start_learning(map()) :: map()
  @callback remember_every_sifat_pair(map()) :: map()
  @callback swipe_study_card_left(map()) :: map()
  @callback swipe_study_card_right(map()) :: map()
  @callback return_to_mission(map()) :: map()
  @callback browser_back_to_mission(map()) :: map()
  @callback study_card_shows?(map(), String.t(), String.t()) :: boolean()
  @callback study_card_colors_attributes?(map()) :: boolean()
  @callback mark_current_pair_remembered(map()) :: map()
  @callback progress_shows?(map(), String.t()) :: boolean()
  @callback ask_reset_sifat_progress(map()) :: map()
  @callback confirm_reset_sifat_progress(map()) :: map()
  @callback start_quiz(map()) :: map()
  @callback quiz_answer_positions_vary?(map()) :: boolean()
  @callback quiz_answer_choices_locked?(map()) :: boolean()
  @callback wait_for_quiz_auto_advance(map()) :: map()
  @callback start_learned_review(map()) :: map()
  @callback start_focused_review(map()) :: map()
  @callback swipe_quiz_question_left(map()) :: map()
  @callback swipe_quiz_question_right(map()) :: map()
  @callback next_quiz_question(map()) :: map()
  @callback answer_quiz(map(), String.t()) :: map()
  @callback answer_focused_review(map(), String.t()) :: map()
  @callback next_focused_review(map()) :: map()
  @callback revision_list_contains?(map(), String.t()) :: boolean()
  @callback establish_identity(map(), :user | :child) :: map()
  @callback prepare_behaviour(map(), atom(), [String.t()]) :: map()
  @callback perform_behaviour(map(), atom(), [String.t()]) :: map()
  @callback behaviour_outcome?(map(), atom(), [String.t()]) :: boolean()
end
