defmodule BnestApp.Behaviour.Driver do
  @moduledoc false

  @callback open(map(), String.t()) :: map()
  @callback brand_logo_visible?(map()) :: boolean()
  @callback installable_as_app?(map()) :: boolean()
  @callback heading_visible?(map(), String.t()) :: boolean()
  @callback text_visible?(map(), String.t()) :: boolean()
  @callback chat_entry_link_visible?(map(), String.t(), String.t()) :: boolean()
  @callback model_selector_lists_all?(map()) :: boolean()
  @callback selected_model?(map(), String.t()) :: boolean()
  @callback effort_selector_lists_supported?(map()) :: boolean()
  @callback selected_effort?(map(), String.t()) :: boolean()
  @callback model_selector_available?(map()) :: boolean()
  @callback model_selector_unavailable?(map()) :: boolean()
  @callback effort_selector_available?(map()) :: boolean()
  @callback effort_selector_unavailable?(map()) :: boolean()
  @callback select_model(map(), String.t()) :: map()
  @callback select_effort(map(), String.t()) :: map()
  @callback conversation_empty?(map()) :: boolean()
  @callback composer_available?(map()) :: boolean()
  @callback composer_unavailable?(map()) :: boolean()
  @callback clear_chat_control_available?(map()) :: boolean()
  @callback attempt_empty_message(map()) :: map()
  @callback send_message(map(), String.t()) :: map()
  @callback submit_with_shift_enter(map(), String.t()) :: map()
  @callback attempt_message_before_finished(map(), String.t()) :: map()
  @callback visitor_message_visible?(map(), String.t()) :: boolean()
  @callback visitor_message_absent?(map(), String.t()) :: boolean()
  @callback stream_codex_response(map()) :: {boolean(), map()}
  @callback one_completed_codex_response_visible?(map()) :: boolean()
  @callback second_codex_response_visible?(map()) :: boolean()
  @callback reject_message(map(), String.t()) :: map()
  @callback report_codex_error(map(), String.t()) :: map()
  @callback alert_visible?(map(), String.t()) :: boolean()
  @callback reload(map()) :: map()
  @callback clear_chat(map()) :: map()
end
